name: Build and Push Base Image

on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag of the base image'
        required: true
        type: string
    outputs:
      image_name:
        description: 'Name of the base image'
        value: ${{ jobs.build-and-push-base-image.outputs.image_name }}

jobs:
  build-and-push-base-image:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.generate_docker_image_name.outputs.image_name }}
    steps:
    - uses: actions/checkout@v4

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Docker Image name
      id: generate_docker_image_name
      run: |
        echo "BASE_TAG=${{ inputs.tag }}" >> $GITHUB_ENV
        IMAGE_NAME="ghcr.io/${{ github.repository }}:base-${{ inputs.tag }}"
        echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

    - name: Build Docker Image
      run: docker compose build base

    - name: Push Docker Image
      run: docker compose push base
