name: Test

on:
  push:
    branches: [ "main" ]
  # Disable pull_request until handle docker image properly
  # pull_request:
  #   branches: [ "main" ]

env:
  BUILD_TYPE: Release
  BASE_TAG: latest
  # Enable if handle merge request 
  # BASE_TAG: ${{ github.run_id }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.generate_docker_image_name.outputs.image_name}}
    steps:
    - uses: actions/checkout@v3

    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Docker Image name
      id: generate_docker_image_name
      run: |
        echo "BASE_TAG=${{env.BASE_TAG}}" >> $GITHUB_ENV
        IMAGE_NAME="ghcr.io/akmaru/cpp-template-project:base-${{env.BASE_TAG}}"
        echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

    - name: Build Docker Image
      run: docker compose build base

    - name: Push Docker Image
      run: docker compose push base

  build:
    needs: build-image
    runs-on: ubuntu-latest
    container: 
      image: ${{ needs.build-image.outputs.image_name }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -GNinja

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build -C ${{env.BUILD_TYPE}}
