name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  BUILD_PATH: build

jobs:
  build-image:
    uses: ./.github/workflows/build-and-push-base-image.yml
    with:
      tag: ci-${{ github.run_id }}
    secrets: inherit

# TODO: Separate the build job into separate jobs, build, test, benchmark and lint-check
#       after resolved the issue https://github.com/actions/upload-artifact/issues/38.
  build:
    needs: build-image
    runs-on: ubuntu-latest
    container: 
      image: ${{ needs.build-image.outputs.image_name }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{env.BUILD_PATH}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -GNinja

    - name: Build
      run: cmake --build ${{env.BUILD_PATH}} --config ${{env.BUILD_TYPE}}
   
    - name: Test
      run: ctest --test-dir ${{env.BUILD_PATH}} -C ${{env.BUILD_TYPE}}

    - name: Benchmark
      run: ${{ env.BUILD_PATH }}/bin/cpp-template_benchmark

    - name: Lint check
      run: ./scripts/lint/check_all.sh ${{ env.BUILD_PATH }}     
